import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'ai_config.dart';

class GeminiService {
  static Future<String> generateResponse(String prompt, {String? model, double temperature = 0.7}) async {
    final apiKey = AiConfig.geminiApiKey;
    if (apiKey.isEmpty || apiKey.contains('YOUR_')) {
      throw Exception('Gemini API key is not configured.');
    }

    final selectedModel = model ?? AiConfig.geminiModel;
    final rawUrl = 'https://generativelanguage.googleapis.com/v1beta/models/$selectedModel:generateContent?key=$apiKey';
    final targetUrl = kIsWeb ? 'https://corsproxy.io/?$rawUrl' : rawUrl;

    try {
      final response = await http.post(
        Uri.parse(targetUrl),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          "contents": [
            {
              "parts": [
                {"text": prompt}
              ]
            }
          ],
          "generationConfig": {
            "temperature": temperature,
          }
        }),
      ).timeout(const Duration(seconds: 30));

      if (response.statusCode != 200) {
        throw Exception('Gemini API error (Status ${response.statusCode}): ${response.body}');
      }

      final data = jsonDecode(response.body);
      final candidates = data['candidates'] as List?;
      if (candidates == null || candidates.isEmpty) {
        throw Exception('No response generated by Gemini.');
      }

      final parts = candidates[0]['content']['parts'] as List?;
      if (parts == null || parts.isEmpty) {
        throw Exception('Empty response parts from Gemini.');
      }

      return parts[0]['text'].toString().trim();
    } catch (e) {
      throw Exception('Gemini Service Error: $e');
    }
  }
}
