import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'ai_config.dart';

class GeminiService {
  static Future<String> generateResponse(String prompt, {String? model, double temperature = 0.7}) async {
    final apiKey = AiConfig.geminiApiKey;
    final selectedModel = model ?? AiConfig.geminiModel;

    final directUrl = 'https://generativelanguage.googleapis.com/v1beta/models/$selectedModel:generateContent?key=$apiKey';
    final payload = jsonEncode({
      "prompt": prompt,
      "model": selectedModel,
      "temperature": temperature,
      "contents": [
        {
          "parts": [
            {"text": prompt}
          ]
        }
      ],
      "generationConfig": {
        "temperature": temperature,
      }
    });

    final headers = {'Content-Type': 'application/json'};
    http.Response? response;

    if (kIsWeb) {
      try {
        response = await http.post(
          Uri.parse('/api/gemini-chat'),
          headers: headers,
          body: payload,
        ).timeout(const Duration(seconds: 10));

        if (response.statusCode != 200 || response.body.contains("<!DOCTYPE")) {
          response = null;
        }
      } catch (_) {
        response = null;
      }
    }

    if (response == null) {
      try {
        response = await http.post(
          Uri.parse(directUrl),
          headers: headers,
          body: payload,
        ).timeout(const Duration(seconds: 30));
      } catch (e) {
        throw Exception('Gemini Service Error: $e');
      }
    }

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final candidates = data['candidates'] as List?;
      if (candidates == null || candidates.isEmpty) {
        throw Exception('No response generated by Gemini.');
      }

      final parts = candidates[0]['content']['parts'] as List?;
      if (parts == null || parts.isEmpty) {
        throw Exception('Empty response parts from Gemini.');
      }

      return parts[0]['text'].toString().trim();
    } else {
      throw Exception('Gemini API error (Status ${response.statusCode}): ${response.body}');
    }
  }
}
