import 'dart:convert';
import 'package:http/http.dart' as http;
import 'ai_config.dart';

class OpenRouterService {
  static const String _baseUrl = 'https://openrouter.ai/api/v1/chat/completions';

  static Future<String> generateResponse(String prompt, {String? model, double temperature = 0.7}) async {
    final apiKey = AiConfig.openRouterApiKey;
    if (apiKey.isEmpty || apiKey.contains('YOUR_')) {
      throw Exception('OpenRouter API key is not configured.');
    }

    final selectedModel = model ?? AiConfig.openRouterModel;

    try {
      final response = await http.post(
        Uri.parse(_baseUrl),
        headers: {
          'Authorization': 'Bearer $apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://ai-learn-mate.app',
          'X-Title': 'Ai Learn Mate',
        },
        body: jsonEncode({
          "model": selectedModel,
          "messages": [
            {"role": "user", "content": prompt}
          ],
          "temperature": temperature,
        }),
      ).timeout(const Duration(seconds: 30));

      if (response.statusCode != 200) {
        throw Exception('OpenRouter API error (Status ${response.statusCode}): ${response.body}');
      }

      final data = jsonDecode(response.body);
      final choices = data['choices'] as List?;
      if (choices == null || choices.isEmpty) {
        throw Exception('No response generated by OpenRouter.');
      }

      return choices[0]['message']['content'].toString().trim();
    } catch (e) {
      throw Exception('OpenRouter Service Error: $e');
    }
  }
}
