import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'ai_config.dart';

class OpenRouterService {
  static const String _baseUrl = 'https://openrouter.ai/api/v1/chat/completions';

  static Future<String> generateResponse(String prompt, {String? model, double temperature = 0.7}) async {
    final apiKey = AiConfig.openRouterApiKey;
    if (apiKey.isEmpty || apiKey.contains('YOUR_')) {
      throw Exception('OpenRouter API key is not configured.');
    }

    final selectedModel = model ?? AiConfig.openRouterModel;
    final payload = jsonEncode({
      "model": selectedModel,
      "messages": [
        {"role": "user", "content": prompt}
      ],
      "temperature": temperature,
    });

    final headers = {
      'Authorization': 'Bearer $apiKey',
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://ai-learn-mate.app',
      'X-Title': 'Ai Learn Mate',
    };

    http.Response? response;

    if (kIsWeb) {
      try {
        response = await http.post(
          Uri.parse('/api/openrouter-chat'),
          headers: headers,
          body: payload,
        ).timeout(const Duration(seconds: 10));

        if (response.statusCode != 200 || response.body.contains("<!DOCTYPE")) {
          response = null;
        }
      } catch (_) {
        response = null;
      }
    }

    if (response == null) {
      try {
        response = await http.post(
          Uri.parse(_baseUrl),
          headers: headers,
          body: payload,
        ).timeout(const Duration(seconds: 30));
      } catch (e) {
        throw Exception('OpenRouter Service Error: $e');
      }
    }

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final choices = data['choices'] as List?;
      if (choices == null || choices.isEmpty) {
        throw Exception('No response generated by OpenRouter.');
      }

      return choices[0]['message']['content'].toString().trim();
    } else {
      throw Exception('OpenRouter API error (Status ${response.statusCode}): ${response.body}');
    }
  }
}
